# Generated by Django 5.1.1 on 2024-09-08 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('file_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioToVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_to_video_audio_file', to='transcriber.mediafile')),
                ('image_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_to_video_image_file', to='transcriber.mediafile')),
                ('video_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_video_file', to='transcriber.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='AudioToText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transcriber.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='TextToAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transcriber.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='VideoToAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_audio_file', to='transcriber.mediafile')),
                ('video_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_file', to='transcriber.mediafile')),
            ],
        ),
    ]
